name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in hashnode posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://rohitkbc.hashnode.dev/rss.xml"
          custom_tags: "imgId/cover_image"
          template: '<table><tr><td><a href="$url"><img width="140px" src="$imgId"></a></td>$newline<td><a href="$url">$title</a></td></tr></table>$newline'
